name: scrape Wikipedia with rvest
on: 
  schedule:
    - cron: '0 0 1 * *'
jobs:
  render:
    runs-on: ubuntu-latest # Change to windows-latest if necessary
    steps:
      - uses: actions/checkout@v3 # Update to the latest version
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("rvest", "tidyverse"))'
      - name: Run script
        run: Rscript scrape_wikipedia.R
