

name: scrape Wikipedia with rvest
on: 
  schedule:
    - cron: '50 * * * *'
jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages(c("rvest", "tidyverse"), type = "win.binary")
        shell: Rscript {0}
      - name: Script
        run: Rscript scrape_wikipedia.R
